// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhotoBook.DesignService.Data;

#nullable disable

namespace PhotoBook.DesignService.Migrations
{
    [DbContext(typeof(DesignDbContext))]
    partial class DesignDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhotoBook.DesignService.Data.DesignTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LayoutJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PhotoSlots")
                        .HasColumnType("integer");

                    b.Property<string>("PreviewUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Category = "Simple",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "One large photo per page",
                            IsActive = true,
                            LayoutJson = "{\"slots\":[{\"x\":0.1,\"y\":0.1,\"width\":0.8,\"height\":0.8}]}",
                            Name = "Single Hero",
                            PhotoSlots = 1,
                            PreviewUrl = ""
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Category = "Simple",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Two photos side by side",
                            IsActive = true,
                            LayoutJson = "{\"slots\":[{\"x\":0.05,\"y\":0.1,\"width\":0.4,\"height\":0.8},{\"x\":0.55,\"y\":0.1,\"width\":0.4,\"height\":0.8}]}",
                            Name = "Side by Side",
                            PhotoSlots = 2,
                            PreviewUrl = ""
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Category = "Grid",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Four photos in a grid",
                            IsActive = true,
                            LayoutJson = "{\"slots\":[{\"x\":0.05,\"y\":0.05,\"width\":0.4,\"height\":0.4},{\"x\":0.55,\"y\":0.05,\"width\":0.4,\"height\":0.4},{\"x\":0.05,\"y\":0.55,\"width\":0.4,\"height\":0.4},{\"x\":0.55,\"y\":0.55,\"width\":0.4,\"height\":0.4}]}",
                            Name = "Grid 4",
                            PhotoSlots = 4,
                            PreviewUrl = ""
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Category = "Mixed",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "One large photo with two smaller ones",
                            IsActive = true,
                            LayoutJson = "{\"slots\":[{\"x\":0.05,\"y\":0.05,\"width\":0.6,\"height\":0.9},{\"x\":0.7,\"y\":0.05,\"width\":0.25,\"height\":0.4},{\"x\":0.7,\"y\":0.55,\"width\":0.25,\"height\":0.4}]}",
                            Name = "Feature + 2",
                            PhotoSlots = 3,
                            PreviewUrl = ""
                        });
                });

            modelBuilder.Entity("PhotoBook.DesignService.Data.PageSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("PhotoBookId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PhotoBookId", "PageNumber");

                    b.ToTable("PageSnapshots");
                });

            modelBuilder.Entity("PhotoBook.DesignService.Data.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BorderStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BorderWidth")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FontSize")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Themes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AccentColor = "#E74C3C",
                            BackgroundColor = "#FFFFFF",
                            BorderColor = "#2C3E50",
                            BorderStyle = "simple",
                            BorderWidth = 2,
                            Description = "Timeless elegance with clean lines",
                            FontFamily = "Georgia",
                            FontSize = 14,
                            IsActive = true,
                            Name = "Classic",
                            PrimaryColor = "#2C3E50",
                            SecondaryColor = "#ECF0F1"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AccentColor = "#FFD700",
                            BackgroundColor = "#FFFFFF",
                            BorderColor = "#000000",
                            BorderStyle = "none",
                            BorderWidth = 0,
                            Description = "Bold and contemporary design",
                            FontFamily = "Helvetica",
                            FontSize = 16,
                            IsActive = true,
                            Name = "Modern",
                            PrimaryColor = "#000000",
                            SecondaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AccentColor = "#CD853F",
                            BackgroundColor = "#FFF8DC",
                            BorderColor = "#8B4513",
                            BorderStyle = "ornate",
                            BorderWidth = 3,
                            Description = "Nostalgic charm with warm tones",
                            FontFamily = "Times New Roman",
                            FontSize = 13,
                            IsActive = true,
                            Name = "Vintage",
                            PrimaryColor = "#8B4513",
                            SecondaryColor = "#F5DEB3"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AccentColor = "#999999",
                            BackgroundColor = "#FFFFFF",
                            BorderColor = "#333333",
                            BorderStyle = "none",
                            BorderWidth = 0,
                            Description = "Clean, simple, and sophisticated",
                            FontFamily = "Arial",
                            FontSize = 12,
                            IsActive = true,
                            Name = "Minimalist",
                            PrimaryColor = "#333333",
                            SecondaryColor = "#F9F9F9"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            AccentColor = "#FF69B4",
                            BackgroundColor = "#FFF0F5",
                            BorderColor = "#C71585",
                            BorderStyle = "rounded",
                            BorderWidth = 2,
                            Description = "Soft pastels and elegant touches",
                            FontFamily = "Brush Script MT",
                            FontSize = 15,
                            IsActive = true,
                            Name = "Romantic",
                            PrimaryColor = "#C71585",
                            SecondaryColor = "#FFE4E1"
                        });
                });

            modelBuilder.Entity("PhotoBook.Shared.Models.PhotoBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Pages")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("PhotoBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
